name       : range-v3
version    : 0.10.0
release    : 1
source     :
    - https://github.com/ericniebler/range-v3/archive/0.10.0.tar.gz : 5a1cd44e7315d0e8dcb1eee4df6802221456a9d1dbeac53da02ac7bd4ea150cd
license    : BSL-1.0
component  : programming.library
summary    : Range library for C++14/17/20, basis for C++20's std::ranges
description: |
    Range library for C++14/17/20. This code was the basis of a formal proposal to add range support to the C++ standard library. That proposal evolved through a Technical Specification, and finally into P0896R4 "The One Ranges Proposal" which was merged into the C++20 working drafts in November 2018.
patterns   : /
setup      : |
    %cmake_ninja -DRANGE_V3_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
